version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__AssistantId=${OPENAI_ASSISTANT_ID}
    volumes:
      - ./backend/Data:/app/Data
    networks:
      - onboarding-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - onboarding-network

networks:
  onboarding-network:
    driver: bridge
